name: Publish Python packages to PyPI
on: push

jobs:
  build-and-publish:
    name: Build and publish Python wheels to PyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        name: Set up Python 3.9
        with:
          python-version: 3.9
      - name: Install Poetry
        run: python -m pip install poetry==1.1.8 --user
      - name: Build
        run: poetry build
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: startsWith(github.ref, 'refs/tags'
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
